### ISSUE TITLE
duplicate patches need cleanup

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#323]
the file https://github.com/eegsynth/eegsynth/blob/master/patches/rhythms/README.md and https://github.com/eegsynth/eegsynth/blob/master/patches/robinson/README.md are exactly the same.

The date of the first commit in `patches/robinson` (10 Nov) aligns with the corresponding blog post. I suspect that the `patches/rythms` was copied from robinson at a later date, but the git log does not provide information. 

@stephenwhitmarsh do you know for what event the rythms patch was used? It might be that it was incorrectly added as part of the http://www.eegsynth.org/?p=1814 documentation reorganization. If so, I propose to delete it. If we can clarify what it was for, we should update the README.

**Comment by stephenwhitmarsh** [comment]
Yes, patches/rythms can be deleted. It was made when we started working on the MIDI clock etc. 
However, a patch that can be used to explain how clocks and triggers are used (with MIDI) would be helpful. Perhaps we could make one using the Doepfer module, due to it being as close to any minimal 'standard' as we can get.
