### ISSUE TITLE
only show warnings and plate once when using eegsynth executable

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#367]
Low priority, but at this moment, when running a list of .ini's, every module outputs the plate (licensing info etc), and the warnings (panda not installed, etc.) as many times as there are modules in the list.

**Comment by robertoostenveld** [comment]
that is because each module runs independently, even though they run in a single terminal. They simply don't know about each other, so I don't know how this could be fixed.

I suggest to close this, also not to clutter the issues list (as it might scare people away to see that there are many unresolved issues).
