### ISSUE TITLE
synchronize2serial conflicts with redis2serial

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#48]

**Comment by robertoostenveld** [comment]
Although the description is not fully clear, I suspect you mean that the synchronize module and the outputcvgate module did not co-interact properly.

Since I did not have a cvgate module (hardware) but did have the parts for a simple 1+1 channel version, I made one in the weekend (based on Arduino nano and a mcp4725 module). So I am now able to test.

The synchronization module had various small bugs in it. I resolved them earlier this evening. I also rewrote the outputcvgate module to use EEGsynth.getfloat. This obsoletes your paasei branch.

Using the fixed synchronization module, it seems to me that it works fine together with the outputcvgate module.

See https://github.com/eegsynth/eegsynth/commit/e0670c7ea62df6bb26455660eba30d7724c613e9
