### ISSUE TITLE
Document old and make new housing for 16 channel EEG

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#74]
The housing for the 8channel OpenBCI board looks great and is robust. Where shall we document the parts @robertoostenveld? Could I make a page on EEGsynth.org/hardware if you send me the stuff?

We will need another housing for the 16channel OpenBCI board, this time with a DSUB connector. Also, this time with the wireless charger. @robertoostenveld, could you give me the specs for your previous order?

**Comment by robertoostenveld** [comment]
since the 8-ch housing was never used - and as we are moving away from touch-proof connectors - I think we should close this issue and not spend too much further time on it. I will add a short README and some photo's to the hardware section on github. 

If we would want a more usable 8-ch enclosure, I think we better 3d-print a new one. That should be wider, so that all connectors can be in a 11x2 arrangement. It should also have an opening to allow replacing the batteries without screws, or a micro-usb connector for charging.
